CREATE SCHEMA IF NOT EXISTS SITE_SHAKA;

CREATE TABLE IF NOT EXISTS `SITE_SHAKA`.`EVENTOS` (
  `ID_EVENTO` INT(11) NOT NULL AUTO_INCREMENT,
  `TP_EVENTO` VARCHAR(25) NOT NULL,
  `NOME_EVENTO` VARCHAR(255) NOT NULL,
  `DATA_EVENTO` DATE NOT NULL,
  PRIMARY KEY (`ID_EVENTO`, `TP_EVENTO`, `NOME_EVENTO`, `DATA_EVENTO`),
  UNIQUE INDEX `ID_EVENTO_UNIQUE` (`ID_EVENTO` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `SITE_SHAKA`.`ESPORTES` (
  `ID_ESPORTE` INT(11) NOT NULL,
  `TP_ESPORTE` VARCHAR(25) NOT NULL,
  `NOME_ESPORTE` VARCHAR(255) NOT NULL,
  `DATA_ESPORTE` DATE NOT NULL,
  `LUGAR_ESPORTE` VARCHAR(255) NOT NULL,
  `VIDEO_ESPORTE` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID_ESPORTE`, `TP_ESPORTE`),
  INDEX `FK_ESPORTES_EVENTOS_idx` (`ID_ESPORTE` ASC, `TP_ESPORTE` ASC, `NOME_ESPORTE` ASC, `DATA_ESPORTE` ASC),
  CONSTRAINT `FK_ESPORTES_EVENTOS`
    FOREIGN KEY (`ID_ESPORTE` , `TP_ESPORTE` , `NOME_ESPORTE` , `DATA_ESPORTE`)
    REFERENCES `SITE_SHAKA`.`EVENTOS` (`ID_EVENTO` , `TP_EVENTO` , `NOME_EVENTO` , `DATA_EVENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
